name: Build and Push Docker Image

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Build project
        run: |
          echo "VITE_SERVICE_ID=$VITE_SERVICE_ID" >> .env
          echo "VITE_TEMPLATE_ID=$VITE_TEMPLATE_ID" >> .env
          echo "VITE_USER_ID=$VITE_USER_ID" >> .env

      - name: Build and push frontend image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nessimntambi/case-management-system:latest
          build-args: |
            NODE_ENV=production
            VITE_SERVICE_ID=${{secrets.VITE_SERVICE_ID}}
            VITE_TEMPLATE_ID=${{secrets.VITE_TEMPLATE_ID}}
            VITE_USER_ID=${{secrets.VITE_USER_ID}}
